In [2]:
import numpy as np

## Some problems. Put your answers inside the print functions

In [3]:
a = np.arange(4).reshape((2,2))

print("array a:")
print(a)

print("\nMaximum value of a:")

print(np.amax(a)) # put your answer inside the print

print("\nMinimum value of a:")
print(np.amin(a)) # put your answer inside the print

print("\nReturn an array of the max in each column of a:")
print(np.amax(a, axis=0)) #takes the max over the rows and return it into columns

print("\nReturn an array of the min in each row of a:")
print(np.amin(a, axis=1)) #across the rows

print("\nReturn a, sorted within each row:")
print(np.sort(a, axis=1)) #sort by least to greatsest 

print("\nReturn a, sorted within each column:")
print(np.sort(a, axis=0)) #axis - operate within what axis

array a:
[[0 1]
 [2 3]]

Maximum value of a:
3

Minimum value of a:
0

Return an array of the max in each column of a:
[2 3]

Return an array of the min in each row of a:
[0 2]

Return a, sorted within each row:
[[0 1]
 [2 3]]

Return a, sorted within each column:
[[0 1]
 [2 3]]


In [18]:
b = np.arange(40).reshape((20,2))
print("array b:")
print(b)

print("\nElements of the first column of b's 80th percentile:")

print(np.percentile(b,80,axis=0)) 

print("\nCovariance matrix of the columns of b:")
print(np.cov(b))



array b:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]
 [34 35]
 [36 37]
 [38 39]]

Elements of the first column of b's 80th percentile:
[30.4 31.4]

Covariance matrix of the columns of b:
[[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
  0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
  0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
  0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
  0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
  0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
  0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
  0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
  0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.