In [1]:
import numpy as np


array a:
[[0 1]
 [2 3]]

Maximum value of a:
3

Minimum value of a:
0

Return an array of the max in each column of a:
[2 3]

Return an array of the min in each row of a:
[0 2]

Return a, sorted within each row:
[[0 1]
 [2 3]]

Return a, sorted within each column:
[[0 1]
 [2 3]]


In [4]:
b = np.arange(40).reshape((20,2))
print("array b:")
print(b)

print("\nPrint elements of the first column of b above that column's 80th percentile:")
print() 

print("\nCovariance matrix of the columns of b:")
print()

array b:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]
 [34 35]
 [36 37]
 [38 39]]

Print elements of the first column of b above that column's 80th percentile:


Covariance matrix of the columns of b:

