In [1]:
data = [
    {'price': 850, 'rooms': 4, 'neighborhood': 'Queen Anne'},
    {'price': 650, 'rooms': 3, 'neighborhood': 'Queen Anne'},
    {'price': 700, 'rooms': 1, 'neighborhood': 'Wallingford'},
    {'price': 650, 'rooms': 3, 'neighborhood': 'Wallingford'},
    {'price': 700, 'rooms': 3, 'neighborhood': 'Fremont'},
    {'price': 600, 'rooms': 2, 'neighborhood': 'Fremont'}
]
data

[{'price': 850, 'rooms': 4, 'neighborhood': 'Queen Anne'},
 {'price': 650, 'rooms': 3, 'neighborhood': 'Queen Anne'},
 {'price': 700, 'rooms': 1, 'neighborhood': 'Wallingford'},
 {'price': 650, 'rooms': 3, 'neighborhood': 'Wallingford'},
 {'price': 700, 'rooms': 3, 'neighborhood': 'Fremont'},
 {'price': 600, 'rooms': 2, 'neighborhood': 'Fremont'}]

In [2]:
import pandas as pd    
from statsmodels.formula.api import ols as sm_ols
print('The coefs from SM:')
print(sm_ols('price ~ neighborhood - 1', data = pd.DataFrame(data)).fit().params)
# ""-1" means no intercept. Don't do this! It's here for illustration

The coefs from SM:
neighborhood[Fremont]        650.0
neighborhood[Queen Anne]     750.0
neighborhood[Wallingford]    675.0
dtype: float64


In [5]:
# create an object ("vec") that can do the transform
from sklearn.feature_extraction import DictVectorizer #load transformation package
vec = DictVectorizer(sparse=False, dtype=int) #takes a dictionary that creates vec

# apply vec with ".fit_transform", save to new data obj
data2 = vec.fit_transform(data) 
print(data2, '\n')              
print(vec.get_feature_names())  # can use .get_feature_names() to recover names

# now we can repeat the regression here
from sklearn.linear_model import LinearRegression
print('Reg coefs:')
LinearRegression(fit_intercept=False).fit(data2[:,:3],data2[:,3]).coef_
#creates dummy variables for each neighborhood
#this data is now ready to regress!

[[  0   1   0 850   4]
 [  0   1   0 650   3]
 [  0   0   1 700   1]
 [  0   0   1 650   3]
 [  1   0   0 700   3]
 [  1   0   0 600   2]] 

['neighborhood=Fremont', 'neighborhood=Queen Anne', 'neighborhood=Wallingford', 'price', 'rooms']
Reg coefs:


array([650., 750., 675.])

In [17]:
# another way to import missing data
import numpy as np
X = np.array([[ np.nan, 0,   3  ],
              [ 3,   7,   9  ],
              [ 3,   5,   2  ],
              [ 4,   np.nan, 6  ],
              [ 8,   8,   1  ]])
print(X,'\n')

# it's this easy:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(strategy='mean')
imp.fit_transform(X) 

[[nan  0.  3.]
 [ 3.  7.  9.]
 [ 3.  5.  2.]
 [ 4. nan  6.]
 [ 8.  8.  1.]] 



array([[4.5, 0. , 3. ],
       [3. , 7. , 9. ],
       [3. , 5. , 2. ],
       [4. , 5. , 6. ],
       [8. , 8. , 1. ]])

# Standardization

In [18]:
# a very simple example
from sklearn import preprocessing
import numpy as np
#load dataset into an array
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])
#apply preprocessing scale to it
X_scaled = preprocessing.scale(X_train)

#subtracts every observation in the array from 1

print(' X_scaled\n',         '-'*40,'\n',X_scaled,'\n')
print(' Mean of each var:\n','-'*40,'\n',X_scaled.mean(axis=0),'\n')
print(' STD of each var:\n', '-'*40,'\n',X_scaled.std(axis=0),'\n')

 X_scaled
 ---------------------------------------- 
 [[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]] 

 Mean of each var:
 ---------------------------------------- 
 [0. 0. 0.] 

 STD of each var:
 ---------------------------------------- 
 [1. 1. 1.] 



## Standardizing Fannie Mae Data

In [19]:
import pandas as pd
#loading the dataset from Fannie Mae
url = 'https://github.com/LeDataSciFi/lectures-spr2020/blob/master/assignment_data/Fannie_Mae_Plus_Data.gzip?raw=true'
fannie_mae = pd.read_csv(url,compression='gzip')  
print(fannie_mae.info())
pd.options.display.float_format = '{:,.1f}'.format
fannie_mae.drop('Loan_Identifier',axis=1).describe().round(1).transpose()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135038 entries, 0 to 135037
Data columns (total 36 columns):
Loan_Identifier                            135038 non-null float64
Origination_Channel                        135038 non-null object
Seller_Name                                135038 non-null object
Original_Interest_Rate                     135038 non-null float64
Original_UPB                               135038 non-null float64
Original_Loan_Term                         135038 non-null float64
Original_LTV_(OLTV)                        135038 non-null float64
Original_Combined_LTV_(CLTV)               134007 non-null float64
Number_of_Borrowers                        135007 non-null float64
Original_Debt_to_Income_Ratio              132396 non-null float64
Borrower_Credit_Score_at_Origination       134481 non-null float64
Loan_purpose                               135038 non-null object
Property_type                              135038 non-null object
Number_of_units       

count      mean       std  \
Original_Interest_Rate                  135,038.0       5.2       1.3   
Original_UPB                            135,038.0 188,931.1 108,742.4   
Original_Loan_Term                      135,038.0     307.1      82.3   
Original_LTV_(OLTV)                     135,038.0      70.1      17.5   
Original_Combined_LTV_(CLTV)            134,007.0      70.9      17.6   
Number_of_Borrowers                     135,007.0       1.6       0.5   
Original_Debt_to_Income_Ratio           132,396.0      33.3      11.5   
Borrower_Credit_Score_at_Origination    134,481.0     742.4      53.4   
Number_of_units                         135,038.0       1.0       0.2   
Zip_code_short                          135,038.0     546.0     306.0   
Primary_mortgage_insurance_percent       24,322.0      23.8       7.2   
Co-borrower_credit_score_at_origination  67,366.0     751.1      50.6   
Mortgage_Insurance_type                  24,322.0       1.1       0.3   
UNRATE                                  135,038.0       6.2       1.7   
CPIAUCSL                                135,038.0     208.2      24.8   
rGDP                                    135,038.0       2.1       2.3   
TCMR                                    135,038.0       3.5       1.2   
POILWTIUSDM                             135,038.0      56.3      27.8   
TTLCONS                                 135,038.0 963,119.3 153,846.4   
DEXUSEU                                 135,038.0       1.2       0.2   
BOPGSTB                                 135,038.0 -42,336.6   9,404.5   
GOLDAMGBD228NLBM                        135,038.0     845.9     498.1   
CSUSHPISA                               135,038.0     148.6      24.7   
MSPUS                                   135,038.0 231,137.7  46,186.1   

                                              min       25%       50%  \
Original_Interest_Rate                        2.2       4.2       5.2   
Original_UPB                              8,000.0 108,000.0 164,000.0   
Original_Loan_Term                           60.0     240.0     360.0   
Original_LTV_(OLTV)                           4.0      60.0      75.0   
Original_Combined_LTV_(CLTV)                  4.0      61.0      75.0   
Number_of_Borrowers                           1.0       1.0       2.0   
Original_Debt_to_Income_Ratio                 1.0      25.0      33.0   
Borrower_Credit_Score_at_Origination        361.0     707.0     755.0   
Number_of_units                               1.0       1.0       1.0   
Zip_code_short                                0.0     295.0     549.0   
Primary_mortgage_insurance_percent            6.0      18.0      25.0   
Co-borrower_credit_score_at_origination     400.0     721.0     765.0   
Mortgage_Insurance_type                       1.0       1.0       1.0   
UNRATE                                        3.8       4.9       5.7   
CPIAUCSL                                    164.7     183.1     212.5   
rGDP                                         -8.4       0.9       2.2   
TCMR                                          1.5       2.3       3.7   
POILWTIUSDM                                  12.0      30.7      48.7   
TTLCONS                                 708,818.0 846,777.0 891,264.0   
DEXUSEU                                       0.9       1.1       1.2   
BOPGSTB                                 -67,823.0 -45,943.0 -41,360.0   
GOLDAMGBD228NLBM                            256.2     350.8     857.7   
CSUSHPISA                                    93.2     130.2     145.6   
MSPUS                                   157,400.0 190,100.0 224,100.0   

                                                75%         max  
Original_Interest_Rate                          6.1        11.0  
Original_UPB                              247,000.0 1,170,000.0  
Original_Loan_Term                            360.0       360.0  
Original_LTV_(OLTV)                            80.0        97.0  
Original_Combined_LTV_(CLTV)                   80.0       142.

In [24]:
from sklearn import preprocessing
import numpy as np

def scale(col_name):
    X_train = fannie_mae[col_name].dropna()
    X_scaled = preprocessing.scale(X_train)
    print(col_name, '\n',         '-'*40,'\n',X_scaled,'\n')
    print(' Mean of each var:\n','-'*40,'\n',X_scaled.mean(axis=0),'\n')
    print(' STD of each var:\n', '-'*40,'\n',X_scaled.std(axis=0),'\n')
    
#convert strings to integers
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
newdf = fannie_mae.select_dtypes(include=numerics)
var_list = newdf.columns
for var in var_list:
    scale(var)

/Users/Kathrynjaco08/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:172: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "


Loan_Identifier 
 ---------------------------------------- 
 [ 1.62279156  1.44667026  0.63847856 ...  0.4227624  -0.15981635
 -0.45726668] 

 Mean of each var:
 ---------------------------------------- 
 -2.4414744693544518e-17 

 STD of each var:
 ---------------------------------------- 
 0.9999999999999999 

Original_Interest_Rate 
 ---------------------------------------- 
 [ 1.26880792  0.49354843  0.78427074 ... -0.47552594 -0.18480363
 -0.08789619] 

 Mean of each var:
 ---------------------------------------- 
 -5.219704037930207e-16 

 STD of each var:
 ---------------------------------------- 
 0.9999999999999999 

Original_UPB 
 ---------------------------------------- 
 [-1.4431508   0.10179076 -0.61550354 ...  0.46043791 -0.88218988
 -0.44997408] 

 Mean of each var:
 ---------------------------------------- 
 2.0205305953278223e-17 

 STD of each var:
 ---------------------------------------- 
 1.0 

Original_Loan_Term 
 ---------------------------------------- 
 [ 0.642

In [25]:
newdf.describe()

Loan_Identifier  Original_Interest_Rate  Original_UPB  \
count         135,038.0               135,038.0     135,038.0   
mean  551,802,281,913.2                     5.2     188,931.1   
std   259,782,148,831.2                     1.3     108,742.4   
min   100,002,000,000.0                     2.2       8,000.0   
25%   327,066,500,000.0                     4.2     108,000.0   
50%   552,532,500,000.0                     5.2     164,000.0   
75%   777,328,250,000.0                     6.1     247,000.0   
max   999,985,000,000.0                    11.0   1,170,000.0   

       Original_Loan_Term  Original_LTV_(OLTV)  Original_Combined_LTV_(CLTV)  \
count           135,038.0            135,038.0                     134,007.0   
mean                307.1                 70.1                          70.9   
std                  82.3                 17.5                          17.6   
min                  60.0                  4.0                           4.0   
25%                 240.0                 60.0                          61.0   
50%                 360.0                 75.0                          75.0   
75%                 360.0                 80.0                          80.0   
max                 360.0                 97.0                         142.0   

       Number_of_Borrowers  Original_Debt_to_Income_Ratio  \
count            135,007.0                      132,396.0   
mean                   1.6                           33.3   
std                    0.5                           11.5   
min                    1.0                            1.0   
25%                    1.0                           25.0   
50%                    2.0                           33.0   
75%                    2.0                           42.0   
max                    8.0                           64.0   

       Borrower_Credit_Score_at_Origination  Number_of_units  ...  CPIAUCSL  \
count                             134,481.0        135,038.0  ... 135,038.0   
mean                                  742.4              1.0  ...     208.2   
std                                    53.4              0.2  ...      24.8   
min                                   361.0              1.0  ...     164.7   
25%                                   707.0              1.0  ...     183.1   
50%                                   755.0              1.0  ...     212.5   
75%                                   786.0              1.0  ...     231.8   
max                                   850.0              4.0  ...     251.2   

           rGDP      TCMR  POILWTIUSDM     TTLCONS   DEXUSEU   BOPGSTB  \
count 135,038.0 135,038.0    135,038.0   135,038.0 135,038.0 135,038.0   
mean        2.1       3.5         56.3   963,119.3       1.2 -42,336.6   
std         2.3       1.2         27.8   153,846.4       0.2   9,404.5   
min        -8.4       1.5         12.0   708,818.0       0.9 -67,823.0   
25%         0.9       2.3         30.7   846,777.0       1.1 -45,943.0   
50%         2.2       3.7         48.7   891,264.0       1.2 -41,360.0   
75%         3.5       4.3         81.9 1,101,187.0       1.3 -36,519.0   
max         7.5       6.7        133.9 1,335,425.0       1.6 -15,946.0   

       GOLDAMGBD228NLBM  CSUSHPISA     MSPUS  
count         135,038.0  135,038.0 135,038.0  
mean              845.9      148.6 231,137.7  
std               498.1       24.7  46,186.1  
min               256.2       93.2 157,400.0  
25%               350.8      130.2 190,100.0  
50%               857.7      145.6 224,100.0  
75%             1,273.6      169.9 258,400.0  
max             1,780.6      202.4 337,900.0  

[8 rows x 25 columns]